### ISSUE TITLE
Project Background

### ISSUE THREAD

**Issue by ustroetz** [refugeehackathon/refugeetransit-website#4]
Hi everyone - I figured it's the easiest if I open an issue. I am just wondering if you have somewhere documented the organization of this project? I really like your idea and would like to help out if that is possible? 
I'm a Python Developer with a special focus on GIS/Maps/Routing and I work for @allyapp.

Feel free to close the ticket if that is the wrong place to ask.

Thanks,
Uli

**Comment by t2d** [comment]
Hi Uli, there is no better way atm. The project just started at the refugeehackathon. No bigger organisation than mail and github. We're not doing Python atm. But all parts (drupal, api, android app, landing page, design) need all the help they can get.

Am 29. Oktober 2015 23:31:24 MEZ, schrieb Uli Stroetz notifications@github.com:

**Comment by johnjohndoe** [comment]
And there is a Slack channel `#migrationguide` here:
- http://de-refugees-slackin.herokuapp.com

**Comment by ustroetz** [comment]
Sounds good. Thanks for getting back. Maybe I can help out a little on the landing page or API, depending how it will be build. Once you are ready with planning maybe you can post tasks as Github Issues.
